/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Candidature = { 'allIndia' : null } |
  { 'maharashtra' : null };
export interface CutoffsRecord {
  'college_name' : string,
  'branch_name' : string,
  'closing_rank' : bigint,
  'seat_type' : string,
  'gender' : string,
  'category' : string,
}
export interface ImportResult {
  'errors' : Array<[bigint, string]>,
  'records_imported' : bigint,
  'total_rows' : bigint,
}
export interface Lead {
  'name' : string,
  'whatsapp' : string,
  'email' : [] | [string],
  'mobile' : string,
  'telegram' : boolean,
}
export interface PredictStep1 {
  'gender' : [] | [string],
  'category' : string,
  'branchName' : [] | [string],
  'college' : [] | [string],
}
export interface Prediction {
  'college_name' : string,
  'branch_name' : string,
  'predicted_rank' : bigint,
  'closing_rank' : bigint,
  'eligible' : boolean,
  'predicted_percentile' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLead' : ActorMethod<
    [string, string, string, boolean, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exportLeadsAsCsv' : ActorMethod<[], string>,
  'getAllLeads' : ActorMethod<[], Array<[bigint, Lead]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCutoffsCount' : ActorMethod<[], bigint>,
  'getCutoffsRange' : ActorMethod<[bigint, bigint], Array<CutoffsRecord>>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getMaxClosingRank' : ActorMethod<[], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importCutoffsCsv' : ActorMethod<[string], ImportResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'predictAdmissionStep1' : ActorMethod<
    [string, PredictStep1, Candidature],
    Array<Prediction>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];