/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CutoffsRecord {
  'college_name' : string,
  'branch_name' : string,
  'closing_rank' : bigint,
  'seat_type' : string,
  'gender' : string,
  'category' : string,
  'percentile' : string,
}
export interface ImportResult {
  'errors' : Array<[bigint, string]>,
  'records_imported' : bigint,
  'total_rows' : bigint,
}
export interface Prediction {
  'college_name' : string,
  'branch_name' : string,
  'closing_rank' : bigint,
}
export interface _SERVICE {
  'getCutoffsCount' : ActorMethod<[], bigint>,
  'getCutoffsRange' : ActorMethod<[bigint, bigint], Array<CutoffsRecord>>,
  'getPredictions' : ActorMethod<
    [string, string, string, string, string],
    Array<Prediction>
  >,
  'importCutoffsCsv' : ActorMethod<[string], ImportResult>,
  'predictAdmission' : ActorMethod<[string], Array<Prediction>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];