/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CutoffsRecord = IDL.Record({
  'college_name' : IDL.Text,
  'branch_name' : IDL.Text,
  'closing_rank' : IDL.Nat,
  'seat_type' : IDL.Text,
  'gender' : IDL.Text,
  'category' : IDL.Text,
});
export const Prediction = IDL.Record({
  'college_name' : IDL.Text,
  'branch_name' : IDL.Text,
  'predicted_rank' : IDL.Nat,
  'closing_rank' : IDL.Nat,
  'eligible' : IDL.Bool,
});
export const ImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  'records_imported' : IDL.Nat,
  'total_rows' : IDL.Nat,
});
export const Candidature = IDL.Variant({
  'allIndia' : IDL.Null,
  'maharashtra' : IDL.Null,
});

export const idlService = IDL.Service({
  'getCutoffsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCutoffsRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CutoffsRecord)],
      ['query'],
    ),
  'getPredictions' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(Prediction)],
      [],
    ),
  'importCutoffsCsv' : IDL.Func([IDL.Text], [ImportResult], []),
  'predictAdmission' : IDL.Func(
      [IDL.Text, Candidature],
      [IDL.Vec(Prediction)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CutoffsRecord = IDL.Record({
    'college_name' : IDL.Text,
    'branch_name' : IDL.Text,
    'closing_rank' : IDL.Nat,
    'seat_type' : IDL.Text,
    'gender' : IDL.Text,
    'category' : IDL.Text,
  });
  const Prediction = IDL.Record({
    'college_name' : IDL.Text,
    'branch_name' : IDL.Text,
    'predicted_rank' : IDL.Nat,
    'closing_rank' : IDL.Nat,
    'eligible' : IDL.Bool,
  });
  const ImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
    'records_imported' : IDL.Nat,
    'total_rows' : IDL.Nat,
  });
  const Candidature = IDL.Variant({
    'allIndia' : IDL.Null,
    'maharashtra' : IDL.Null,
  });
  
  return IDL.Service({
    'getCutoffsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCutoffsRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CutoffsRecord)],
        ['query'],
      ),
    'getPredictions' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(Prediction)],
        [],
      ),
    'importCutoffsCsv' : IDL.Func([IDL.Text], [ImportResult], []),
    'predictAdmission' : IDL.Func(
        [IDL.Text, Candidature],
        [IDL.Vec(Prediction)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };