/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ImportResult {
    errors: Array<[bigint, string]>;
    records_imported: bigint;
    total_rows: bigint;
}
export interface CutoffsRecord {
    college_name: string;
    branch_name: string;
    closing_rank: bigint;
    seat_type: string;
    gender: string;
    category: string;
}
export interface Prediction {
    college_name: string;
    branch_name: string;
    predicted_rank: bigint;
    closing_rank: bigint;
    eligible: boolean;
}
export enum Candidature {
    allIndia = "allIndia",
    maharashtra = "maharashtra"
}
export interface backendInterface {
    getCutoffsCount(): Promise<bigint>;
    getCutoffsRange(start: bigint, limit: bigint): Promise<Array<CutoffsRecord>>;
    getPredictions(college: string, branch: string, category: string, gender: string, seat_type: string): Promise<Array<Prediction>>;
    importCutoffsCsv(csvText: string): Promise<ImportResult>;
    predictAdmission(userPercentile: string, candidature: Candidature): Promise<Array<Prediction>>;
}
import type { Candidature as _Candidature } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCutoffsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCutoffsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCutoffsCount();
            return result;
        }
    }
    async getCutoffsRange(arg0: bigint, arg1: bigint): Promise<Array<CutoffsRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCutoffsRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCutoffsRange(arg0, arg1);
            return result;
        }
    }
    async getPredictions(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictions(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictions(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async importCutoffsCsv(arg0: string): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importCutoffsCsv(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importCutoffsCsv(arg0);
            return result;
        }
    }
    async predictAdmission(arg0: string, arg1: Candidature): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.predictAdmission(arg0, to_candid_Candidature_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.predictAdmission(arg0, to_candid_Candidature_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function to_candid_Candidature_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Candidature): _Candidature {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Candidature): {
    allIndia: null;
} | {
    maharashtra: null;
} {
    return value == Candidature.allIndia ? {
        allIndia: null
    } : value == Candidature.maharashtra ? {
        maharashtra: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
